#ifndef CPC_TERMINAL_H
#define CPC_TERMINAL_H

#include "cpc_base.h"

#ifdef CPC_PLATFORM_WINDOWS
	#define WIN32_LEAN_AND_MEAN
	#include <Windows.h>
	#undef WIN32_LEAN_AND_MEAN
	
	#define CPC_TERMINAL_FOREGROUND_BLACK         (0)
	#define CPC_TERMINAL_FOREGROUND_DARK_RED      (FOREGROUND_RED)
	#define CPC_TERMINAL_FOREGROUND_DARK_GREEN    (FOREGROUND_GREEN)
	#define CPC_TERMINAL_FOREGROUND_DARK_YELLOW   (FOREGROUND_RED | FOREGROUND_GREEN)
	#define CPC_TERMINAL_FOREGROUND_DARK_BLUE     (FOREGROUND_BLUE)
	#define CPC_TERMINAL_FOREGROUND_DARK_MAGENTA  (FOREGROUND_RED | FOREGROUND_BLUE)
	#define CPC_TERMINAL_FOREGROUND_DARK_CYAN     (FOREGROUND_GREEN | FOREGROUND_BLUE)
	#define CPC_TERMINAL_FOREGROUND_LIGHT_GRAY    (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE)
	#define CPC_TERMINAL_FOREGROUND_DARK_GRAY     (FOREGROUND_INTENSITY)
	#define CPC_TERMINAL_FOREGROUND_LIGHT_RED     (FOREGROUND_INTENSITY | FOREGROUND_RED)
	#define CPC_TERMINAL_FOREGROUND_LIGHT_GREEN   (FOREGROUND_INTENSITY | FOREGROUND_GREEN)
	#define CPC_TERMINAL_FOREGROUND_LIGHT_YELLOW  (FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN)
	#define CPC_TERMINAL_FOREGROUND_LIGHT_BLUE    (FOREGROUND_INTENSITY | FOREGROUND_BLUE)
	#define CPC_TERMINAL_FOREGROUND_LIGHT_MAGENTA (FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE)
	#define CPC_TERMINAL_FOREGROUND_LIGHT_CYAN    (FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE)
	#define CPC_TERMINAL_FOREGROUND_WHITE         (FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE)

	#define CPC_TERMINAL_BACKGROUND_BLACK         (0)
	#define CPC_TERMINAL_BACKGROUND_DARK_RED      (BACKGROUND_RED)
	#define CPC_TERMINAL_BACKGROUND_DARK_GREEN    (BACKGROUND_GREEN)
	#define CPC_TERMINAL_BACKGROUND_DARK_YELLOW   (BACKGROUND_RED | BACKGROUND_GREEN)
	#define CPC_TERMINAL_BACKGROUND_DARK_BLUE     (BACKGROUND_BLUE)
	#define CPC_TERMINAL_BACKGROUND_DARK_MAGENTA  (BACKGROUND_RED | BACKGROUND_BLUE)
	#define CPC_TERMINAL_BACKGROUND_DARK_CYAN     (BACKGROUND_GREEN | BACKGROUND_BLUE)
	#define CPC_TERMINAL_BACKGROUND_LIGHT_GRAY    (BACKGROUND_INTENSITY)
	#define CPC_TERMINAL_BACKGROUND_DARK_GRAY     (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE)
	#define CPC_TERMINAL_BACKGROUND_LIGHT_RED     (BACKGROUND_INTENSITY | BACKGROUND_RED)
	#define CPC_TERMINAL_BACKGROUND_LIGHT_GREEN   (BACKGROUND_INTENSITY | BACKGROUND_GREEN)
	#define CPC_TERMINAL_BACKGROUND_LIGHT_YELLOW  (BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN)
	#define CPC_TERMINAL_BACKGROUND_LIGHT_BLUE    (BACKGROUND_INTENSITY | BACKGROUND_BLUE)
	#define CPC_TERMINAL_BACKGROUND_LIGHT_MAGENTA (BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE)
	#define CPC_TERMINAL_BACKGROUND_LIGHT_CYAN    (BACKGROUND_INTENSITY | BACKGROUND_GREEN | BACKGROUND_BLUE)
	#define CPC_TERMINAL_BACKGROUND_WHITE         (BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE)

	typedef WORD CPCTerminalStyle;
#else
	#define CPC_TERMINAL_FOREGROUND_BLACK         "\x1B[30m"
	#define CPC_TERMINAL_FOREGROUND_DARK_RED      "\x1B[31m"
	#define CPC_TERMINAL_FOREGROUND_DARK_GREEN    "\x1B[32m"
	#define CPC_TERMINAL_FOREGROUND_DARK_YELLOW   "\x1B[33m"
	#define CPC_TERMINAL_FOREGROUND_DARK_BLUE     "\x1B[34m"
	#define CPC_TERMINAL_FOREGROUND_DARK_MAGENTA  "\x1B[35m"
	#define CPC_TERMINAL_FOREGROUND_DARK_CYAN     "\x1B[36m"
	#define CPC_TERMINAL_FOREGROUND_LIGHT_GRAY    "\x1B[37m"
	#define CPC_TERMINAL_FOREGROUND_DARK_GRAY     "\x1B[90m"
	#define CPC_TERMINAL_FOREGROUND_LIGHT_RED     "\x1B[91m"
	#define CPC_TERMINAL_FOREGROUND_LIGHT_GREEN   "\x1B[92m"
	#define CPC_TERMINAL_FOREGROUND_LIGHT_YELLOW  "\x1B[93m"
	#define CPC_TERMINAL_FOREGROUND_LIGHT_BLUE    "\x1B[94m"
	#define CPC_TERMINAL_FOREGROUND_LIGHT_MAGENTA "\x1B[95m"
	#define CPC_TERMINAL_FOREGROUND_LIGHT_CYAN    "\x1B[96m"
	#define CPC_TERMINAL_FOREGROUND_WHITE         "\x1B[97m"

	#define CPC_TERMINAL_BACKGROUND_BLACK         "\x1B[40m"
	#define CPC_TERMINAL_BACKGROUND_DARK_RED      "\x1B[41m"
	#define CPC_TERMINAL_BACKGROUND_DARK_GREEN    "\x1B[42m"
	#define CPC_TERMINAL_BACKGROUND_DARK_YELLOW   "\x1B[43m"
	#define CPC_TERMINAL_BACKGROUND_DARK_BLUE     "\x1B[44m"
	#define CPC_TERMINAL_BACKGROUND_DARK_MAGENTA  "\x1B[45m"
	#define CPC_TERMINAL_BACKGROUND_DARK_CYAN     "\x1B[46m"
	#define CPC_TERMINAL_BACKGROUND_LIGHT_GRAY    "\x1B[47m"
	#define CPC_TERMINAL_BACKGROUND_DARK_GRAY     "\x1B[100m"
	#define CPC_TERMINAL_BACKGROUND_LIGHT_RED     "\x1B[101m"
	#define CPC_TERMINAL_BACKGROUND_LIGHT_GREEN   "\x1B[102m"
	#define CPC_TERMINAL_BACKGROUND_LIGHT_YELLOW  "\x1B[103m"
	#define CPC_TERMINAL_BACKGROUND_LIGHT_BLUE    "\x1B[104m"
	#define CPC_TERMINAL_BACKGROUND_LIGHT_MAGENTA "\x1B[105m"
	#define CPC_TERMINAL_BACKGROUND_LIGHT_CYAN    "\x1B[106m"
	#define CPC_TERMINAL_BACKGROUND_WHITE         "\x1B[107m"

	typedef const char *CPCTerminalStyle;
#endif

void cpc_terminal_init(void);
void cpc_terminal_apply_style(CPCTerminalStyle style);
void cpc_terminal_reset_style(void);
void cpc_terminal_set_cursor_pos(unsigned short x, unsigned short y);
void cpc_terminal_get_size(unsigned short *restrict width, unsigned short *restrict height);

#endif
